import type { Match, StageType, TournamentStage } from './tournament.ts';

/**
 * Pure result-correction predicate.
 *
 * A recorded result is normally immutable: a completed match cannot be scored a
 * second time. The original tournament application, however, lets an operator
 * re-enter a mistyped group score (`saveGroupScore`), and the TASK-5 parity
 * audit records the missing workflow as gap G6. This module is the single
 * source of truth for *what* may be corrected; the application service owns the
 * transactional re-scoring.
 *
 * Both stage types are correctable now. A **group** correction is a plain
 * re-score - standings and qualification are derived from the stored games, so
 * they correct automatically. A **knockout** correction additionally re-derives
 * the bracket (the immediate destination slot is re-filled with the new winner
 * and every already-decided downstream match is reset), which the application
 * service performs in the same transaction.
 *
 * The stage **type** is the discriminator, never the match's `roundNumber` /
 * `matchNumber`: a group fixture generated by the round-robin carries the
 * round-robin round in `roundNumber` (and its generation index in
 * `matchNumber`), so those fields are populated for group matches too. The
 * predicate has no runtime dependency.
 */

/**
 * True exactly when a match's result may be corrected: it is `COMPLETED` and it
 * belongs to a correctable stage type. Any non-completed match - scheduled, in
 * progress or cancelled - has no recorded result to correct. The stage type is
 * checked as a set so a hypothetical future stage type is never silently treated
 * as correctable.
 */
const CORRECTABLE_STAGE_TYPES: readonly StageType[] = ['GROUP', 'KNOCKOUT'];

export function isMatchCorrectable(match: Match, stage: TournamentStage): boolean {
  return match.status === 'COMPLETED' && CORRECTABLE_STAGE_TYPES.includes(stage.type);
}
