import type { Match, TournamentStage } from './tournament.ts';

/**
 * Pure result-correction predicate.
 *
 * A recorded result is normally immutable: a completed match cannot be scored a
 * second time. The original tournament application, however, lets an operator
 * re-enter a mistyped group score (`saveGroupScore`), and the TASK-5 parity
 * audit records the missing workflow as gap G6. This module is the single
 * source of truth for *what* may be corrected; the application service owns the
 * transactional re-scoring.
 *
 * The scope is deliberately **group-only**. Correcting a knockout result also
 * requires re-deriving the bracket (clearing the winner from the next round and
 * un-completing every downstream match), which is a separate workflow; a
 * knockout match therefore stays immutable.
 *
 * The stage **type** is the discriminator, never the match's `roundNumber` /
 * `matchNumber`: a group fixture generated by the round-robin carries the
 * round-robin round in `roundNumber` (and its generation index in
 * `matchNumber`), so those fields are populated for group matches too. A
 * knockout stage's matches are the only ones whose result feeds a bracket, and
 * `type === 'GROUP'` is the same signal the scoring path uses to pick the
 * match format. The predicate has no runtime dependency.
 */

/**
 * True exactly when a match's result may be corrected: it is `COMPLETED` and it
 * belongs to a `GROUP` stage. Any non-completed match - scheduled, in progress
 * or cancelled - has no recorded result to correct, and a knockout match cannot
 * be corrected without re-deriving the bracket.
 */
export function isMatchCorrectable(match: Match, stage: TournamentStage): boolean {
  return match.status === 'COMPLETED' && stage.type === 'GROUP';
}
