import { loadEnvironmentFiles } from '@badminton/config';
import { connectDatabase, type PrismaClient } from '@badminton/database';

/**
 * Development seed.
 *
 * Idempotent and deterministic: every row is resolved from a natural key and
 * then upserted (or updated in place), so running the seed repeatedly converges
 * on the same state and never duplicates rows. No UUID is hard-coded - ids are
 * generated by the database and rediscovered on each run.
 *
 * The tournament dataset is deliberately tiny. It exists to prove the Phase 2
 * schema, constraints and relations work end to end, not to generate a draw.
 */

interface SeedEntry {
  readonly key: string;
  readonly value: string;
}

const FOUNDATION_METADATA: readonly SeedEntry[] = [
  { key: 'schema.version', value: '2' },
  { key: 'schema.phase', value: '2-tournament-database' },
  { key: 'seed.version', value: '2' },
];

/** Deterministic player fixtures, keyed by the email used for lookup. */
const PLAYERS = [
  { name: 'Player A', email: 'player.a@example.test' },
  { name: 'Player B', email: 'player.b@example.test' },
  { name: 'Player C', email: 'player.c@example.test' },
  { name: 'Player D', email: 'player.d@example.test' },
] as const;

const TOURNAMENT = {
  name: 'Community Badminton Tournament',
  description: 'Deterministic development fixture for the Phase 2 tournament schema.',
  startDate: new Date('2026-10-03T00:00:00.000Z'),
  endDate: new Date('2026-10-05T00:00:00.000Z'),
  location: 'Community Sports Hall',
  timezone: 'Asia/Kolkata',
  status: 'DRAFT',
} as const;

const TEAM_NAME = 'Player A + Player B';

async function seedFoundation(prisma: PrismaClient): Promise<void> {
  for (const entry of FOUNDATION_METADATA) {
    await prisma.systemMetadata.upsert({
      where: { key: entry.key },
      update: { value: entry.value },
      create: { key: entry.key, value: entry.value },
    });
  }
}

/** Creates or updates the fixture tournament, returning its id. */
async function seedTournament(prisma: PrismaClient): Promise<string> {
  const existing = await prisma.tournament.findFirst({
    where: { name: TOURNAMENT.name, status: 'DRAFT' },
    select: { id: true },
  });

  if (existing) {
    await prisma.tournament.update({ where: { id: existing.id }, data: TOURNAMENT });
    return existing.id;
  }

  const created = await prisma.tournament.create({
    data: TOURNAMENT,
    select: { id: true },
  });
  return created.id;
}

/** Creates or updates a player, matching on the deterministic email. */
async function seedPlayer(prisma: PrismaClient, player: (typeof PLAYERS)[number]): Promise<string> {
  const existing = await prisma.player.findFirst({
    where: { email: player.email },
    select: { id: true },
  });

  if (existing) {
    await prisma.player.update({ where: { id: existing.id }, data: { name: player.name } });
    return existing.id;
  }

  const created = await prisma.player.create({
    data: { name: player.name, email: player.email },
    select: { id: true },
  });
  return created.id;
}

async function seed(prisma: PrismaClient): Promise<void> {
  await seedFoundation(prisma);

  const tournamentId = await seedTournament(prisma);

  const categoryIds = new Map<string, string>();
  for (const category of [
    { code: 'MS', name: "Men's Singles", format: 'SINGLES', gender: 'MALE' },
    { code: 'MD', name: "Men's Doubles", format: 'DOUBLES', gender: 'MALE' },
  ] as const) {
    const row = await prisma.tournamentCategory.upsert({
      where: { tournamentId_code: { tournamentId, code: category.code } },
      update: { name: category.name, format: category.format, gender: category.gender },
      create: {
        tournamentId,
        code: category.code,
        name: category.name,
        format: category.format,
        gender: category.gender,
        status: 'OPEN',
      },
      select: { id: true },
    });
    categoryIds.set(category.code, row.id);
  }

  const playerIds = new Map<string, string>();
  for (const player of PLAYERS) {
    playerIds.set(player.name, await seedPlayer(prisma, player));
  }

  const existingTeam = await prisma.team.findFirst({
    where: { name: TEAM_NAME },
    select: { id: true },
  });
  const teamId = existingTeam
    ? existingTeam.id
    : (await prisma.team.create({ data: { name: TEAM_NAME }, select: { id: true } })).id;

  for (const [position, name] of ['Player A', 'Player B'].entries()) {
    const playerId = playerIds.get(name);
    if (!playerId) {
      throw new Error(`Seed fixture is missing player ${name}.`);
    }
    await prisma.teamMember.upsert({
      where: { teamId_playerId: { teamId, playerId } },
      update: { position: position + 1 },
      create: { teamId, playerId, position: position + 1 },
    });
  }

  const singlesId = categoryIds.get('MS');
  const doublesId = categoryIds.get('MD');
  const playerAId = playerIds.get('Player A');
  const playerCId = playerIds.get('Player C');
  if (!singlesId || !doublesId || !playerAId || !playerCId) {
    throw new Error('Seed fixtures are incomplete.');
  }

  // Two singles entries so the seeded match has two sides; one doubles entry.
  const entryIds = new Map<string, string>();
  for (const [key, where] of [
    ['singles-a', { categoryId: singlesId, playerId: playerAId }],
    ['singles-c', { categoryId: singlesId, playerId: playerCId }],
    ['doubles-ab', { categoryId: doublesId, teamId }],
  ] as const) {
    const existing = await prisma.tournamentEntry.findFirst({
      where,
      select: { id: true },
    });

    if (existing) {
      await prisma.tournamentEntry.update({
        where: { id: existing.id },
        data: { status: 'CONFIRMED' },
      });
      entryIds.set(key, existing.id);
    } else {
      const created = await prisma.tournamentEntry.create({
        data: { ...where, status: 'CONFIRMED' },
        select: { id: true },
      });
      entryIds.set(key, created.id);
    }
  }

  const stage = await prisma.tournamentStage.upsert({
    where: { categoryId_sequence: { categoryId: singlesId, sequence: 1 } },
    update: { name: 'Group Stage', type: 'GROUP', status: 'PENDING' },
    create: {
      categoryId: singlesId,
      name: 'Group Stage',
      type: 'GROUP',
      sequence: 1,
      drawSize: 4,
      status: 'PENDING',
    },
    select: { id: true },
  });

  const match = await prisma.match.upsert({
    where: { stageId_sequence: { stageId: stage.id, sequence: 1 } },
    update: { status: 'SCHEDULED' },
    create: { stageId: stage.id, sequence: 1, matchNumber: 1, status: 'SCHEDULED' },
    select: { id: true },
  });

  for (const [slot, entryKey] of [
    [1, 'singles-a'],
    [2, 'singles-c'],
  ] as const) {
    const entryId = entryIds.get(entryKey);
    if (!entryId) {
      throw new Error(`Seed fixture is missing entry ${entryKey}.`);
    }
    await prisma.matchParticipant.upsert({
      where: { matchId_slot: { matchId: match.id, slot } },
      update: { entryId },
      create: { matchId: match.id, entryId, slot },
    });
  }
}

async function main(): Promise<void> {
  loadEnvironmentFiles();

  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error('DATABASE_URL is required to run the seed. Copy .env.example to .env first.');
  }

  const database = connectDatabase(connectionString);

  try {
    await seed(database.prisma);
    process.stdout.write(
      `Seed complete: ${FOUNDATION_METADATA.length} metadata rows and the tournament fixture upserted.\n`,
    );
  } finally {
    await database.disconnect();
  }
}

main().catch((error: unknown) => {
  process.stderr.write('Seed failed.\n');
  if (error instanceof Error) {
    process.stderr.write(`${error.message}\n`);
  }
  process.exit(1);
});
