import { isMatchCorrectable, type Match, type TournamentStage } from '@badminton/domain';
import { describe, expect, it } from 'vitest';

/**
 * Result-correction predicate.
 *
 * The rule is pure, so it is proven here without a database: a result may be
 * corrected only for a completed match that belongs to a **group** stage. The
 * stage type is the discriminator - a group fixture generated by the
 * round-robin carries a `roundNumber`/`matchNumber`, so those fields cannot
 * distinguish a group match from a knockout one. A match that has not completed
 * has no recorded result to correct.
 */

function match(overrides: Partial<Match> = {}): Match {
  const now = new Date('2026-01-01T00:00:00.000Z');
  return {
    id: '88888888-8888-4888-8888-888888888888',
    stageId: '77777777-7777-4777-8777-777777777777',
    sequence: 1,
    roundNumber: null,
    matchNumber: null,
    status: 'COMPLETED',
    winnerEntryId: '66666666-6666-4666-8666-666666666666',
    knockoutFormat: null,
    knockoutPointsPerGame: null,
    courtId: null,
    scheduledStartAt: null,
    scheduledEndAt: null,
    createdAt: now,
    updatedAt: now,
    ...overrides,
  };
}

function stage(overrides: Partial<TournamentStage> = {}): TournamentStage {
  const now = new Date('2026-01-01T00:00:00.000Z');
  return {
    id: '77777777-7777-4777-8777-777777777777',
    categoryId: '55555555-5555-4555-8555-555555555555',
    name: 'Group A',
    type: 'GROUP',
    sequence: 1,
    drawSize: null,
    qualifiersPerGroup: null,
    knockoutRules: null,
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    ...overrides,
  };
}

describe('isMatchCorrectable', () => {
  it('is true for a completed match in a GROUP stage', () => {
    expect(isMatchCorrectable(match(), stage())).toBe(true);
  });

  it('is true for a real group fixture that carries a round-robin round', () => {
    // The round-robin generator stamps the round-robin round onto the match, so
    // the bracket-position fields are populated for group matches too; the
    // predicate must ignore them and read the stage type.
    expect(
      isMatchCorrectable(match({ roundNumber: 1, matchNumber: 1 }), stage({ type: 'GROUP' })),
    ).toBe(true);
  });

  it('is false for a completed match in a KNOCKOUT stage', () => {
    expect(isMatchCorrectable(match(), stage({ type: 'KNOCKOUT' }))).toBe(false);
    expect(
      isMatchCorrectable(
        match({ roundNumber: 1, matchNumber: 1 }),
        stage({ type: 'KNOCKOUT', sequence: 2 }),
      ),
    ).toBe(false);
  });

  it('is false for any non-completed match', () => {
    for (const status of ['SCHEDULED', 'IN_PROGRESS', 'CANCELLED'] as const) {
      expect(isMatchCorrectable(match({ status }), stage())).toBe(false);
    }
  });
});
